[project]
name = "arcadia-interview-sft"
version = "0.1.0"
description = "SFT spurious correlation interview question"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "transformers",
    "matplotlib",
    "peft",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/arcadia_interview_sft"]
